version: 2.1

commands:
  build-app:
    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - './node_modules'
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: yarn lint

      - run: yarn size

      - run: yarn test
  deploy-firebase:
    parameters:
      firebase-project:
        type: string
        default: '$FIREBASE_PROJECT'
    steps:
      - run:
          name: Deploy to Firebase
          command: ./node_modules/.bin/firebase deploy --token "$FIREBASE_CI_TOKEN" --project "<< parameters.firebase-project >>"

orbs:
  codecov: codecov/codecov@1.0.2

jobs:
  build:
    docker:
      - image: circleci/node:12.9.1-browsers

    working_directory: ~/repo
    steps:
      - build-app

  deploy_dev:
    docker:
      - image: circleci/node:12.9.1-browsers

    working_directory: ~/repo
    steps:
      - build-app
      - codecov/upload:
          file: './coverage'
      - deploy-firebase:
          firebase-project: $FIREBASE_PROJECT_DEV

workflows:
  version: 2
  build_deploy_dev:
    jobs:
      - deploy_dev:
          filters:
            branches:
              only:
                - dev
